# Generated by Django 4.0.4 on 2022-04-27 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_note_created_alter_note_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.DateTimeField()),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.note')),
            ],
        ),
    ]
