# Generated by Django 4.0.4 on 2022-04-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_note_created_alter_note_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='audio',
            field=models.FileField(blank=True, help_text='Audio related to Note', upload_to='audios/'),
        ),
    ]
