# Generated by Django 4.0.4 on 2022-04-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
